---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(scales)
theme_set(theme_light())

tuesdata <- tt_load(2020, week = 52)

big_mac <- tuesdata$`big-mac` %>% 
  rename("country" = "name") %>% 
  add_count(country, name = "country_total")
```

```{r}
big_mac %>% 
  filter(country_total == max(country_total)) %>% 
  mutate(country = fct_reorder(country, local_price, function(.) min(.) / max(.))) %>% 
  ggplot(aes(date, local_price, color = country)) +
  geom_line() +
  expand_limits(y = 0) +
  facet_wrap(~ country, scales = "free_y") +
  theme(legend.position = "none") +
  labs(x = "Time", 
       y = "Price of Big Mac in local currency")
  
```
```{r}
big_mac %>% 
  filter(country_total == max(country_total)) %>% 
  group_by(country) %>% 
  summarize(big_mac_inflation = last(local_price) / first(local_price)) %>% 
  mutate(country = fct_reorder(country, big_mac_inflation)) %>% 
  ggplot(aes(big_mac_inflation, country)) +
  geom_col() + 
  geom_text(aes(label = paste0(round(big_mac_inflation, 1), "X")), hjust = 0) +
  scale_x_log10(breaks = c(1, 3, 10, 30, 100)) 
```

