---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
theme_set(theme_classic())

genron_poll <- 
  read_excel("genron_npo.xlsx") %>% 
  rename(year = "...1") %>% 
  mutate(year = as.character(year),
         year = paste0(year, "-01-01"), 
         year = ymd(year))
```

```{r}
percent <- function(x) (x / 100)

genron_poll <- genron_poll %>% mutate_if(is.numeric, percent)

genron_poll %>% 
  rename("Favorable" = china_f, 
         "Unfavorable" = china_u) %>% 
  gather(china, value, Favorable, Unfavorable) %>% 
  ggplot(aes(x = year, value, color = china)) +
  geom_point() +
  geom_line(size = 2) + 
  scale_y_continuous(limits = c(0, 1), 
                     breaks = seq(0, 1, .1), 
                     labels = scales::percent_format()) +
  theme(legend.position = "bottom") +
  scale_color_discrete(labels = c("Favorable", "Unfavorable")) + 
  scale_colour_manual(values = c("blue", "red")) +
  labs(title = "Chinese view toward Japan has been improving", 
       x = "Year", 
       y = " ", 
       color = " ", 
       caption = "Source: GenronNPO") +
  theme(plot.title = element_text(face = "bold", hjust = .5, size = 15))
ggsave(filename = "chinese_view_toward_japan.pdf", width = 8, height = 5)
  
```

```{r}
genron_poll %>% 
  rename("Favorable" = japan_f, 
         "Unfavorable" = japan_u) %>% 
  gather(china, value, Favorable, Unfavorable) %>% 
  ggplot(aes(x = year, y = value, color = china)) +
  geom_point() +
  geom_line(size = 2) + 
  scale_y_continuous(limits = c(0, 1), 
                     breaks = seq(0, 1, .1), 
                     labels = scales::percent_format()) +
  theme(legend.position = "bottom") +
  scale_color_discrete(labels = c("Favorable", "Unfavorable")) + 
  scale_colour_manual(values = c("blue", "red")) +
  labs(title = "Japanese Public Opinion toward China: Favorable / Unfavorable", 
       x = "Year", 
       y = " ", 
       color = " ", 
       caption = "Source: GenronNPO") +
  theme(plot.title = element_text(face = "bold", hjust = .5, size = 15))
ggsave(filename = "japanese_view_toward_china.pdf", width = 8, height = 5)
```

