---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_light())

nyc_squirrels <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-29/nyc_squirrels.csv")
```

```{r}
nyc_squirrels %>% 
  ggplot(aes(long, lat)) +
  geom_point()

nyc_squirrels %>% count(hectare, sort = T)

by_hectare <- nyc_squirrels %>% 
  filter(!is.na(primary_fur_color)) %>% 
  group_by(hectare) %>% 
  summarize(long = mean(long), 
            lat = mean(lat),
            pct_gray = mean(primary_fur_color == "Gray", na.rm = T), 
            n = n())

by_hectare %>% 
  filter(n >= 10) %>% 
  ggplot(aes(long, lat, size = n, color = pct_gray)) + 
  geom_point() +
  theme_void()

by_hectare %>% 
  filter(n >= 10) %>% 
  ggplot(aes(lat, pct_gray)) +
  geom_point() +
  geom_smooth()
  
```
Are there patterns of colors in terms of territory? 

```{r}
by_hectare %>% 
  mutate(n_gray = round(pct_gray * n)) %>% 
  glm(cbind(n_gray, n - n_gray) ~ lat, data = ., family = "binomial") %>% 
  summary()
```
Squirrels may be more likely to be gray the higher north in the park you go, and more likely to be cinammon / black. 

```{r}
nyc_squirrels %>% 
  count(approaches, sort = T)
```
Does a squirrel run away?

```{r}
glm(runs_from ~ lat, data = nyc_squirrels, family = "binomial") %>% 
  summary()
```

```{r}
library(sf)

central_park_sf <- read_sf("~/Downloads/CentralParks/")

ggplot(central_park_sf) +
  geom_sf()

nyc_squirrels %>% 
  add_count(hectare) %>% 
  group_by(hectare, n) %>% 
  summarize_at(vars(long, lat, runs_from, indifferent), mean) %>% 
  filter(n >= 10) %>% 
  ungroup() %>%
  ggplot(aes(long, lat, size = n, color = runs_from)) + 
  geom_point() +
  theme_void() + 
  scale_color_gradient2(low = "blue", 
                        high = "red", 
                        mid = "pink", 
                        midpoint = .3, 
                        labels = scales::percent) +
  labs(color = "% of squirrels run", 
       size = "# of squirrels")
  
```


