---
title: "Untitled"
author: "Jaehwan Lim"
date: "December 19, 2018"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(janitor)
library(lubridate)

set.seed(20181209)

# You can use this url to download the data directly into R (will take a few seconds)
restaurant_inspections_raw <- read_csv("https://data.cityofnewyork.us/api/views/43nn-pn8j/rows.csv")

# Cleaning names with janitor, sampling 300,000 records, and dropping some variables
restaurant_inspections <- restaurant_inspections_raw %>% 
        clean_names() %>%
        select(-phone, -grade_date, -record_date, -building, -street) %>% 
        sample_n(size = 300000) %>%
        mutate(inspection_date = mdy(inspection_date)) %>%
        separate(inspection_type, c("inspection_program", "inspection_type"), sep = " / ", )

theme_set(theme_light())

```

```{r}
## see if each row is distinct in what terms
restaurant_inspections %>% 
  count(dba, camis, inspection_date, sort = T)

restaurant_inspections %>% 
  count(year = year(inspection_date)) 

restaurant_inspections %>% 
  count(violation_description, sort = T) %>% 
  head() %>% 
  pull(violation_description)
  
inspections <- restaurant_inspections %>% 
  group_by(camis, 
           dba,
           boro,
           zipcode,
           cuisine_description,
           inspection_date,
           action, 
           score, 
           grade, 
           inspection_type, 
           inspection_program) %>%
  summarize(critical_violations = sum(critical_flag == "Critical", na.rm = T), 
            noncritical_violations = sum(critical_flag == "Not Critical", na.rm = T)) %>% 
  ungroup()

most_recent_cycle_inspections <- inspections %>% 
  filter(inspection_program == "Cycle Inspection", 
         inspection_type == "Initial Inspection") %>% 
  arrange(desc(inspection_date)) %>% 
  distinct(camis, .keep_all = TRUE)

```

## Which type of cuisine is more likely to get higher scores (e.g., more violations)?

```{r}
library(broom)

by_cuisine <- most_recent_cycle_inspections %>% 
  group_by(cuisine_description) %>% 
  summarize(avg_score = mean(score), 
            median_score = median(score), 
            restaurant = n()) %>% 
  arrange(desc(restaurant))

cuisine_conf_ints <- most_recent_cycle_inspections %>% 
  add_count(cuisine_description) %>% 
  filter(n > 200) %>% 
  nest(-cuisine_description) %>% 
  mutate(model = map(data, ~ t.test(.$score))) %>% 
  unnest(map(model, tidy))

cuisine_conf_ints %>% 
  mutate(cuisine_description = str_remove(cuisine_description, " \\(.*"), 
         cuisine_description = fct_reorder(cuisine_description, estimate)) %>% 
  ggplot(aes(cuisine_description, estimate)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high, width = 0.2)) + 
  coord_flip() + 
  labs(x = "Type of cuisine", 
       y = "Average inspection scores (higher means more violoations)")

```

## Does the # of locations affect the distribution of score?

```{r}
by_dba <- most_recent_cycle_inspections %>% 
  group_by(dba, cuisine = cuisine_description) %>% 
  summarize(avg_score = mean(score), 
            median_score = median(score), 
            locations = n()) %>% 
  arrange(desc(locations)) %>% 
  ungroup()

by_dba
```

```{r}
by_dba %>% 
  ggplot(aes(locations, mean_score)) + 
  geom_point() + 
  scale_x_log10()
```

```{r}
by_dba %>% 
  mutate(locations_bin = cut(locations, c(0, 1, 3, 10, Inf), 
                         labels = c("1", "2-3", "3-10", ">10"))) %>% 
  ggplot(aes(locations_bin, median_score + 1)) + 
  geom_boxplot() +
  scale_y_log10()
  
```

## Are there some violations that are more common in particular type of cuisine than in others?

```{r}
violation_cuisine_counts <- restaurant_inspections %>% 
  semi_join(most_recent_cycle_inspections, by = c("camis", "inspection_date")) %>%
  count(critical_flag, violation_code, violation_description, cuisine = cuisine_description) %>% 
  group_by(violation_code) %>% 
  mutate(violation_total = sum(n)) %>% 
  group_by(cuisine) %>% 
  mutate(cuisine_total = sum(n)) %>%
  ungroup() %>% 
  filter(violation_total >= 1000, 
         cuisine_total >= 2000) %>%
  group_by(violation_description) %>% 
  mutate(fraction = n / cuisine_total,
         avg_fraction = mean(fraction)) %>% 
  ungroup() 

violation_cuisine_counts %>% 
  ## interesting approach to calculate risk 
  mutate(relative_risk = fraction / avg_fraction) %>%
  arrange(desc(relative_risk)) %>%
  filter(violation_description == "Live roaches present in facility's food and/or non-food areas.") 
```

## What violations tend to occur together?

```{r}
library(widyr)
library(irlba)

violations <- restaurant_inspections %>% 
  semi_join(most_recent_cycle_inspections, by = c("camis", "inspection_date")) %>% 
  filter(!is.na(violation_description)) 

violations %>% 
  pairwise_cor(violation_description, camis, sort = TRUE)

principal_components <- violations %>% 
  mutate(value = 1) %>% 
  widely_svd(violation_description, camis, value, nv = 6) 

principal_components %>% 
  filter(dimension == 3)
  
```

