---
title: "Untitled"
author: "Jaehwan Lim"
date: "January 8, 2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

tidytuesday_tweets <- read_rds(url("https://github.com/rfordatascience/tidytuesday/blob/master/data/2019/2019-01-01/tidytuesday_tweets.rds?raw=true"))

theme_set(theme_light())

```

```{r}
library(lubridate)

tidytuesday_tweets %>% 
  count(date = floor_date(created_at, "month")) %>% 
  ggplot(aes(x = date, y = n)) +
  geom_line() +
  expand_limits(y = 0) +
  labs(x = "Time", 
       y = "# of tweets")
```

```{r}
tidytuesday_tweets %>% 
  count(screen_name, sort = T) %>% 
  mutate(screen_name = fct_reorder(screen_name, n)) %>% 
  head(n = 12) %>% 
  ggplot(aes(x = screen_name, y = n)) +
  geom_col() +
  coord_flip()
```

```{r}
tidytuesday_tweets %>% 
  group_by(screen_name) %>% 
  summarize(tweets = n(), 
            retweets = sum(retweet_count)) %>% 
  arrange(desc(tweets)) %>% 
  arrange(desc(retweets))
  
tidytuesday_tweets %>% 
  select(screen_name, retweet_count, favorite_count, text) %>% 
  mutate(ratio = (favorite_count + 1) / (retweet_count + 1)) %>% 
  arrange(desc(ratio))
  
```

```{r}
library(tidytext)

tweet_words <- 
  tidytuesday_tweets %>% 
  select(screen_name, text, retweet_count, favorite_count, created_at) %>% 
  unnest_tokens(word, text, token = "tweets") %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(word != "#tidytuesday")
  
tweet_words %>% 
  count(word, sort = T) %>% 
  head(16) %>%
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(x = word, y = n)) +
  geom_col() +
  coord_flip() + 
  labs(title = "Most common words in #tidytuesday tweets", 
       x = "Frequency of words", 
       y = "# of words")
  
```


