---
title: "Untitled"
author: "Jaehwan Lim"
date: "January 6, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stringr)

theme_set(theme_light())

tv_ratings <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/9749b0ef5c5f6690df98fb5bdbbec57e01c35bd5/data/2019/2019-01-08/IMDb_Economist_tv_ratings.csv")

```

```{r}
library(lubridate)

tv_ratings %>% 
  count(date = floor_date(date, "year")) %>% 
  ggplot(aes(x = date, y = n)) +
  geom_line() + 
  labs(x = "Year", 
       y = "# of titles")

tv_ratings %>% 
  group_by(title) %>% 
  mutate(avg_share = mean(share)) %>% 
  ungroup() %>% 
  mutate(title = fct_reorder(title, avg_share)) %>% 
  arrange(desc(avg_share)) %>% 
  distinct(title, .keep_all = T) %>% 
  head(15) %>% 
  ggplot(aes(x = title, y = avg_share)) + 
  geom_col() + 
  coord_flip()
```

### Has TV been getting better or worse over time? 

```{r}
library(lubridate)

## aggregating numbers by year
by_year <- tv_ratings %>% 
  group_by(year = 2 * (year(date) %/% 2)) %>% 
  summarize(mean_rating = mean(av_rating), 
            median_rating = median(av_rating),
            mean_season1 = mean(av_rating[seasonNumber == 1]), 
            mean_season = mean(seasonNumber),
            sd_rating = sd(av_rating), 
            observations = n()) 

## Plotting every metric into a single graph by using gather
by_year %>% 
  gather(metric, value, -year, -observations, -mean_season, -sd_rating) %>% 
  ggplot(aes(year, value, color = metric)) +
  geom_line() 

## Plotting mean_rating for seasonNumber
tv_ratings %>% 
  group_by(year = 5 * (year(date) %/% 5), 
           seasonNumber = ifelse(seasonNumber >= 4, "+4", seasonNumber)) %>%
  summarize(mean_rating = mean(av_rating), 
            observations = n()) %>% 
  ggplot(aes(year, mean_rating, color = factor(seasonNumber))) +
  geom_line() + 
  labs(color = "Season", 
       y = "Average rating in each 5-year period")
```

### Show survival
If season 1 is good, what is the probability that they get season 2?

```{r}
first_three_seasons <- tv_ratings %>% 
  filter(seasonNumber <= 3) %>% 
  group_by(title) %>% 
  mutate(first_date = min(date)) %>% 
  ungroup() %>% 
  transmute(title, 
            seasonNumber = str_c("season", seasonNumber, sep = ""), 
            first_date,
            av_rating) %>% 
  distinct(title, seasonNumber, .keep_all = TRUE) %>% 
  spread(seasonNumber, av_rating) %>% 
  filter(!is.na(season1)) %>% 
  filter(first_date <= "2017-01-01")
  
library(broom)

glm(!is.na(season2) ~ season1, data = first_three_seasons) %>% 
  tidy()

```

```{r}
first_three_seasons %>% 
  ## originally, ntile function was used instead of cut fuction, namely, group_by(ntile(season1, 5))
  group_by(season1_bin = cut(season1, c(0, 7, 7.5, 8, 8.5, 10))) %>% 
  summarize(had_second_season = mean(!is.na(season2)), 
            observations = n()) %>% 
  ## why need to add group = 1? It's because, "For line graphs, the data points must be grouped so that it knows which points to connect. In this case, it is simple -- all points should be connected, so group=1. When more variables are used and multiple lines are drawn, the grouping for lines is usually done by variable."
  ggplot(aes(x = season1_bin, y = had_second_season, group = 1)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = scales::percent_format())

first_three_seasons %>% 
  group_by(season1_bin = cut(season1, c(0, 7, 7.5, 8, 8.5, 10)), 
           time_bin = ifelse(first_date < "2000-01-01", "Before 2000", "After 2000")) %>% 
  summarize(had_second_season = mean(!is.na(season2)), 
            observations = n()) %>% 
  ggplot(aes(x = season1_bin, 
             y = had_second_season, 
             color = time_bin, 
             group = time_bin)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = scales::percent_format())

```

## Visualizing the interaction term of year and season1

```{r}


new_data <- crossing(
  year = 1990:2018, 
  season1 = seq(6, 9)
)

first_three_seasons %>% 
  mutate(year = year(first_date), 
         had_second_season = !is.na(season2)) %>% 
  glm(had_second_season ~ season1 * year, data = ., family = "binomial") %>% 
  ## learn how to use "augment" function
  augment(newdata = new_data, type.predict = "response") %>% 
  ggplot(aes(year, .fitted, color = factor(season1))) +
  geom_line() + 
  scale_y_continuous(labels = scales::percent_format()) + 
  labs(title = "Probability of getting season 2 has become more dependent on the ratings of season 1", 
       color = "Season1 rating", 
       y = "Predicted probability")

## another plot 
library(splines)

mod <- first_three_seasons %>% 
  mutate(year = year(first_date), 
         had_second_season = !is.na(season2)) %>% 
  glm(had_second_season ~ season1 * year, data = ., family = "binomial") 

summary(mod) 

mod %>% 
  ## learn how to use "augment" function
  augment(newdata = new_data, type.predict = "response") %>% 
  ggplot(aes(year, .fitted, color = factor(season1))) +
  geom_line() + 
  scale_y_continuous(labels = scales::percent_format()) + 
  labs(title = "Probability of getting season 2 has become more dependent on the ratings of season 1", 
       color = "Season1 rating", 
       y = "Predicted probability of getting season 2")
  
```

```{r}
tv_ratings %>%
  filter(seasonNumber <= 7) %>% 
  group_by(seasonNumber) %>% 
  summarize(av_rating = mean(av_rating)) %>% 
  ggplot(aes(x = seasonNumber, y = av_rating)) +
  geom_line()


```

