---
title: "unvoting"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(lubridate)
theme_set(theme_light())
```



```{r Load}
tt <- tt_load("2021-03-23")

unvotes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/unvotes.csv')
roll_calls <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/roll_calls.csv')
issues <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-23/issues.csv')

roll_calls %>% 
  count(short, sort = T)

issues %>% 
  count(issue, sort = T)
```



```{r}
unvotes <- unvotes %>% mutate(vote = match(vote, c("no", "abstain", "yes")) - 2)
```



```{r}
# Which country has voted for resolutions most often?
by_country <- unvotes %>% 
  group_by(country) %>% 
  summarize(n = n(), 
            yes_ratio = mean(vote == 1)) 

by_country_filtered <- by_country %>% 
  filter(n >= 100) %>% 
  arrange(desc(yes_ratio))

by_country_filtered %>% 
  head(20) %>% 
  mutate(country = fct_reorder(country, yes_ratio)) %>% 
  ggplot(aes(yes_ratio, country)) +
  geom_point(aes(size = n)) +
  scale_x_continuous(labels = percent) +
  labs(title = "% of yes votes in UNGM", 
       y = " ", 
       size = "# of votes")

by_country_filtered %>% 
  tail(20) %>%  
  mutate(country = fct_reorder(country, yes_ratio)) %>% 
  ggplot(aes(yes_ratio, country)) +
  geom_point(aes(size = n)) +
  scale_x_continuous(labels = percent) +
  labs(title = "What countries voted yest the least in UNGM?", 
       y = " ", 
       size = "# of votes")
  
```



```{r}
unvotes_joined <- unvotes %>% 
  left_join(roll_calls, by = "rcid") %>% 
  mutate(year = year(date))

unvotes_joined %>% 
  count(short, sort = T)

unvotes_joined %>% 
  group_by(country, year) %>% 
  summarize(n = n(), 
            yes_ratio = mean(vote == 1)) %>% 
  filter(country == "China") %>% 
  ggplot(aes(year, yes_ratio)) +
  geom_point(aes(size = n)) +
  geom_line() +
  expand_limits(y = 0.5)

```



```{r}
library(ggthemes) 
library(countrycode)

map_data_mutated <- map_data("world") %>% 
  tibble() %>% 
  filter(region != "Antarctica") %>%
  mutate(iso3c = countrycode(region, "country.name", "iso3c"))

map_data_mutated %>% 
  ggplot(aes(long, lat, group = group)) +
  geom_polygon() +
  theme_map()

# Mapping out the distribution of yes-ratio 

by_country_filtered %>% 
  mutate(iso3c = countrycode(country, "country.name", "iso3c")) %>% 
  left_join(map_data_mutated, by = "iso3c") %>% 
  ggplot(aes(long, lat, group = group, fill = yes_ratio)) +
  geom_polygon() +
  theme_map()

```


### Correlation between nations


```{r}
library(widyr)

## How China and the U.S. has correlated with each other over time across issue areas?

unvotes_joined %>% 
  filter(country %in% c("United States", "China"), 
         year >= 1971) %>%
  left_join(issues, by = "rcid") %>% 
  filter(!is.na(issue)) %>% 
  select(rcid, country, vote, issue, year) %>% 
  pivot_wider(names_from = "country", values_from = "vote", values_fill = 0) %>% 
  group_by(year = 10 * (year %/% 10), issue) %>% 
  summarize(correlation = cor(`China`, `United States`)) %>% 
  ggplot(aes(year, correlation)) +
  geom_point() +
  geom_line(size = 1) +
  facet_wrap(~ issue) +
  labs(title = "Correlation in UN Voting between China nad US across issue areas (each decade)", 
       x = "Year")
```


### Which countries supported most and least the US at UNGA?


```{r}
unvotes %>% 
  select(-country_code) %>% 
  pairwise_cor(country, rcid, vote) %>% 
  filter(item2 == "United States", 
         !is.na(correlation)) %>% 
  arrange(desc(correlation)) %>% 
  mutate(item1 = fct_reorder(item1, correlation)) %>% 
  slice(c(1:15, (n() - 10):n())) %>% 
  ggplot(aes(correlation, item1)) +
  geom_errorbarh(height = 0, aes(xmin = 0, xmax = correlation)) +
  geom_point() +
  labs(title = "How much these countries' votings were correlated with the US?", 
       y = " ")
 
```

### Two kinds of machine learning: 

### Principal component analysis


```{r}
unvotes_df <- unvotes %>% 
  select(country, rcid, vote) %>% 
  mutate(vote = factor(vote, levels = c("no", "abstain", "yes")), 
         vote = as.numeric(vote), 
         rcid = paste0("rcid_", rcid)) %>% 
  pivot_wider(names_from = rcid, values_from = vote, values_fill = 2)
```




```{r}
library(recipes)

pca_recipe <- recipe(~., data = unvotes_df) %>% 
  update_role(country, new_role = "id") %>% 
  step_normalize(all_predictors()) %>% 
  step_pca(all_predictors())

pca_prep <- prep(pca_recipe)  
```



```{r}
bake(pca_prep, new_data = NULL) %>% 
  ggplot(aes(PC1, PC2, label = country)) +
  geom_point(color = "midnightblue", alpha = .7, size = 2) +
  geom_text(check_overlap = TRUE, hjust = "inward")
```

