---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

dolphin_us <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-12-18/allCetaceanData.csv") %>% 
  select(-X1) %>% 
  # transform the type of variables (chr -> integer in the case of year)
  mutate(birthYear = as.integer(birthYear))

theme_set(theme_light())

```

```{r}
library(lubridate)

dolphin_us %>% 
  filter(status == "Died") %>% 
  filter(!is.na(birthYear), !is.na(statusDate)) %>% 
  ## transform the type of variables (year -> integer)
  mutate(age = year(statusDate) - birthYear) %>% 
  ggplot(aes(age)) +
  geom_histogram()

dolphin_us %>%
  filter(status == "Died") %>% 
  filter(!is.na(birthYear), !is.na(statusDate)) %>% 
  ## transform the type of variables (year -> integer)
  mutate(age = year(statusDate) - birthYear) %>% 
  group_by(species) %>% 
  filter(n > 20) %>% 
  summarize(avg_age = median(age)) %>% 
  mutate(species = fct_reorder(species, n)) %>% 
  ggplot(aes(species, avg_age)) +
  geom_col() +
  coord_flip()

```

```{r}
dolphin_us %>%
  ggplot(aes(originDate, fill = acquisition)) +
  geom_histogram()

dolphin_us %>%
  filter(originDate > "1960-01-01") %>% 
  count(acquisition, 
        decade = 5 * (year(originDate) %/% 5)) %>% 
  ## look at how to fill the annoying gap in the graph
  complete(decade, acquisition, fill = list(n = 0)) %>% 
  mutate(acquisition = fct_reorder(acquisition, n, sum)) %>% 
  group_by(decade) %>% 
  mutate(prop = n / sum(n)) %>% 
  ggplot(aes(decade, prop, fill = acquisition)) +
  geom_area() +
  geom_vline(linetype = 2, xintercept = 1979) + 
  scale_y_continuous(labels = scales::percent_format()) +
  ## also look at a technic of tidying plots
  theme_minimal() +
  labs(y = "% of dolphins recorded", 
       x = "")

```
### Survival analysis

```{r}
library(survival)

dolphin_survival <- dolphin_us %>% 
  filter(status %in% c("Alive", "Died")) %>% 
  mutate(statusDate = ifelse(status == "Alive", 2017, year(statusDate)), 
         status = ifelse(status == "Alive", 0, 1), 
         age = statusDate - birthYear) %>% 
  filter(!is.na(statusDate)) %>% 
  select(birthYear, statusDate, status, sex, acquisition, species)

survfit(Surv(birthYear, statusDate, status) ~ 1, dolphin_survival)


```


