---
title: "Untitled"
author: "Jaehwan Lim"
date: "February 6, 2019"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

milkcow_facts <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/milkcow_facts.csv")

milk_sales <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/fluid_milk_sales.csv")

milk_products <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/milk_products_facts.csv")

clean_cheese <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/clean_cheese.csv")

state_production <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-29/state_milk_production.csv")

theme_set(theme_light())

```

```{r}
state_production %>% 
  group_by(region) %>% 
  summarize(total_production = sum(milk_produced)) %>%
  mutate(region = fct_reorder(region, total_production)) %>% 
  ggplot(aes(region, total_production)) +
  geom_col() + 
  coord_flip()
```

```{r}
state_production %>% 
  group_by(region, year) %>% 
  summarize(total_production = sum(milk_produced)) %>% 
  ggplot(aes(year, total_production)) +
  geom_line() +
  facet_wrap(~ region)

```

```{r}
## tidying the dataset
milk_products_tidied <- milk_products %>% 
  gather(product, value, -year) %>%
  # look at how to use the categories within the values using separate
  separate(product, c("category", "product"), sep = "_", 
           # look at how to use separate arguments 
           extra = "merge", fill = "right") %>% 
  # look at how to use coalesce (if the product is NA, drop back to category)
  mutate(product = coalesce(product, category), 
         product = str_to_title(str_replace_all(product, "_", " ")), 
         category = str_to_title(category)) 
```

```{r}
milk_products_tidied %>% 
  group_by(year, category) %>% 
  mutate(total_consumption = sum(value)) %>% 
  ggplot(aes(year, total_consumption)) + 
  geom_line() + 
  facet_wrap(~ product, scales = "free") + 
  expand_limits(y = 0)
```

```

