---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(lubridate)
library(scales)
theme_set(theme_light())
```

```{r}
water <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-04/water.csv') %>% 
  rename("lat" = "lat_deg", 
         "lon" = "lon_deg", 
         "country" = "country_name")

water <- water %>% 
  mutate(report_date = mdy(report_date)) %>% 
  filter(between(lat, -30, 30), 
         between(lon, -40, 60))
  
```


```{r}
water %>% 
  count(country, sort = T)

water %>% 
  ggplot(aes(x = install_year, y = ..density.., fill = status_id)) +
  geom_histogram(position = "identity", alpha = .7)
  
```


## Drawing Maps 


```{r}
library(maps)
library(countrycode)
library(ggthemes)

africa_map_data <- 
  map_data("world") %>% 
  as.tibble() %>% 
  mutate(continent = countrycode(region, "country.name", "continent")) %>% 
  filter(continent == "Africa")
```




```{r}
water_nigeria <- water %>% 
  filter(country == "Nigeria", 
         between(lon, 1, 18), 
         between(lat, 0, 15)) 

water_nigeria %>% 
  ggplot(aes(lon, lat, color = status_id)) +
  borders("world", regions = "Nigeria") +
  geom_point(alpha = .25, 
             size = .1) +
  scale_color_discrete(guide = guide_legend(override.aes = list(size = 2, alpha = 1))) +
  theme_map()
```





```{r}
library(ggmap)

bbox <- c(left = 2, bottom = 3, right = 15, top = 14)

ggmap_nigeria <- get_stamenmap(bbox, zoom = 8)
```





```{r}
ggmap(ggmap_nigeria) +  
  geom_point(data = water_nigeria_source_filtered, aes(lon, lat), alpha = .25, size = .1) +
  facet_wrap(~ water_source)

water_nigeria_source_filtered <- water_nigeria %>% 
  filter(water_source %in% c("Borehole", "Protected Shallow Well", "Protected Spring"))

```
