---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(tidytext)
theme_set(theme_light())

tt <- tt_load("2021-02-09")
```

```{r}
income_distribution <- tt$income_distribution
income_time <- tt$income_time
income_limits <- tt$income_limits
income_aggregate <- tt$income_aggregate
income_mean <- tt$income_mean

str(income_distribution)
glimpse(income_distribution)
summary(income_distribution)

income_distribution %>% 
  count(year)

income_distribution %>% 
  count(race)

income_distribution %>% 
  count(income_bracket)

```

```{r}
lifetime_earn <- tt$lifetime_earn

lifetime_earn %>% 
  ggplot(aes(lifetime_earn, race, fill = gender)) +
  geom_col(position = "dodge") +
  scale_x_continuous(labels = dollar)
```

```{r}
plot_by_race <- function(data, column, labels = dollar, ...) {
  last_year <- data %>% 
    group_by(race) %>% 
    top_n(1, year)  
    
  data %>% 
    mutate(race = fct_reorder(race, -{{ column }}, last)) %>% 
    ggplot(aes(year, {{ column }}, color = race, ...)) +
    geom_line(size = 1) +
    geom_text(aes(label = race, color = NULL), 
              hjust = 0, 
              nudge_x = .2,
              data = last_year) +
    expand_limits(y = 0, 
                  x = 2020) +
    scale_y_continuous(labels = labels) +
    theme(legend.position = "none") +
    labs(x = "Year")
}

tt$student_debt %>% 
  plot_by_race(loan_debt) +
  labs(y = "Average family student loan debt (for aged 25-55)")

tt$student_debt %>% 
  plot_by_race(loan_debt_pct, labels = percent) +
  labs(y = "Share of families with student loan debt")

tt$retirement %>% 
  plot_by_race(retirement) +
  labs(title = "Average family liquid retirement savings (normalized to 2016 dollars)", 
       y = " ")

tt$home_owner %>% 
  plot_by_race(home_owner_pct, labels = percent) +
  labs(title = "Home ownership percentage for families", 
       y = " ")

tt$race_wealth %>% 
  plot_by_race(wealth_family) + 
  facet_wrap(~ type, scales = "free_y")

```

```{r}
tt$income_time %>% 
  mutate(percentile = fct_reorder(percentile, income_family)) %>% 
  ggplot(aes(year, income_family, color = percentile)) +
  geom_line()

tt$income_time %>% 
  spread(percentile, income_family) %>% 
  ggplot(aes(year, `50th`, ymin = `10th`, ymax = `90th`)) +
  geom_line() +
  geom_ribbon(alpha = .25) +
  scale_y_continuous(labels = dollar) +
  labs(x = " ", 
       y = "Family income (median with 10th and 90th percentile")

tt$income_limits
```



