---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_light())

wine_rating <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv") %>% select(-X1) %>% extract(title, "year", regex = "([12][90]\\d\\d)", convert = TRUE, remove = FALSE) %>% filter(year > 1900)

```

```{r}
glimpse(wine_rating)

wine_rating %>% count(country, sort = T)

wine_rating %>% count(country, province, sort = T)

wine_rating %>% count(designation, sort = T)

wine_rating %>% count(variety, sort = T)

wine_rating %>% 
  ggplot(aes(price)) +
  geom_histogram() + 
  scale_x_log10()

wine_rating %>% 
  ggplot(aes(points)) +
  geom_histogram(binwidth = 1)
```

# Start machine learning
```{r}
wine_rating %>% 
  ggplot(aes(year)) +
  geom_histogram()

wine_rating %>% 
  ggplot(aes(price, points)) +
  geom_point(alpha = .1) +
  scale_x_log10() +
  geom_smooth(method = "lm")

summary(lm(points ~ log2(price), data = wine_rating)) 
# Everytime the price doubles, the points go up by about 2. 
```

# Fitting a linear regression to predict wine ratings based on country, taster, and variety
```{r}
wine_rating %>% 
  lm(points ~ log2(price), data = .) %>% 
  summary()

wine_rating %>% 
  replace_na(list(taster_name = "Missing")) %>% 
  mutate(country = fct_relevel(fct_lump(country, 7), "US"),
         taster_name = fct_relevel(fct_lump(taster_name, 6), "Missing")) %>% 
  lm(points ~ log2(price) + country + year + taster_name, data = .) %>% 
  summary()
```

# Detecting the pattern without controlling for other factors
```{r}
wine_rating %>% 
  mutate(country = fct_relevel(fct_lump(country, 7), "US")) %>% 
  mutate(country = fct_reorder(country, points)) %>% 
  ggplot(aes(country, points)) + 
  geom_boxplot() +
  coord_flip()

wine_rating %>% 
  ggplot(aes(year, points, group = year)) +
  geom_boxplot() + 
  coord_flip()
```

# Visualizing the model - plotting coefficient plot
```{r}
library(broom)

mod <- wine_rating %>% 
  replace_na(list(taster_name = "Missing")) %>% 
  mutate(country = fct_relevel(fct_lump(country, 7), "US"),
         taster_name = fct_relevel(fct_lump(taster_name, 6), "Missing")) %>% 
  lm(points ~ log2(price) + country + year + taster_name, data = .)

mod %>% tidy(conf.int = TRUE) %>% 
  filter(term != "(Intercept)") %>% 
  mutate(term = fct_reorder(term, estimate)) %>% 
  ggplot(aes(term, estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high, width = .2)) +
  geom_hline(aes(yintercept = 0), color = "red", lty = "dashed") +
  coord_flip()
```

# Checking with the fitness of the model
```{r}
mod %>% 
  augment(data = wine_rating) %>% 
  ggplot(aes(.fitted, points)) +
  geom_point(alpha = .1)

tidy(anova(mod)) %>% 
  mutate(sumsq / sum(sumsq))
# 37 % of the variance in points can be explained by the price
```

### Lasso regression in description

```{r}
library(tidytext)

wine_rating_tokens <- wine_rating %>% 
  mutate(review_id = row_number()) %>% 
  unnest_tokens(word, description) %>% 
  anti_join(stop_words, by = "word") %>% 
  filter(!word %in% c("wine", "drink")) 

wine_rating_tokens %>% 
  count(word, sort = T) %>% 
  head(20) %>% 
  mutate(word = fct_reorder(word, n)) %>% 
  ggplot(aes(word, n)) + 
  geom_col() +
  coord_flip()
```


```{r}
library(widyr)

wine_rating_filtered <- wine_rating_tokens %>% 
  distinct(review_id, word) %>% 
  add_count(word) %>% 
  filter(n >= 1000, 
         str_detect(word, "[a-z]")) 

wine_rating_cors <- wine_rating_filtered %>% 
  pairwise_cor(word, review_id, sort = T)

```

```{r}
library(Matrix)

# Predictor variable
wine_word_matrix <- wine_rating_filtered %>% 
  cast_sparse(review_id, word)

# Response variable
wine_ids <- as.integer(rownames(wine_word_matrix))
scores <- wine_rating$points[wine_ids]

nrow(wine_word_matrix)
length(scores)

library(glmnet)

glm_model <- glmnet(wine_word_matrix, scores)
glm_model

glm_model %>% 
  tidy() %>%
  filter(term %in% c("rich", "black", "simple")) %>% 
  ggplot(aes(lambda, estimate, color = term)) +
  geom_line() +
  scale_x_log10()


```

```{r}
wine_rating_processed <- wine_rating %>% 
  mutate(country = fct_lump(country, 6), 
         taster_name = fct_lump(taster_name, 10), 
         variety = fct_lump(variety, 15)) %>% 
  replace_na(list(country = "Other", 
                  taster_name = "Other", 
                  variety = "Other"))

wine_rating_processed %>% 
  select(country, points, price, taster_name, variety) %>% 
  gather(category, value, -points, -price) %>% 
  count(category, value) %>% 
  group_by(category) %>% 
  top_n(15, n) %>% 
  ungroup() %>% 
  mutate(value = fct_reorder(value, n)) %>% 
  ggplot(aes(value, n)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~ category, scales = "free_y")
```
