---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
options(scipen=999)

## data load in
jobs_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/jobs_gender.csv")
earnings_female <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/earnings_female.csv") 
employed_gender <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-05/employed_gender.csv") 

```

```{r}
earnings_female %>% 
  ggplot(aes(Year, percent, color = group)) +
  geom_line()
```

```{r}
## aggregating the values
summarize_jobs_gender <- function (tbl) {
  tbl %>% 
    summarize(total_total_workers = sum(total_workers), 
              total_workers_male = sum(workers_male), 
              total_workers_female = sum(workers_female),
              total_earnings = sum(total_earnings * total_workers) / sum(total_workers), 
              total_earnings_male = sum(total_earnings_male * workers_male, na.rm = T) / sum(workers_male), 
              total_earnings_female = sum(total_earnings_female * workers_female, na.rm = T) / sum(workers_female)
              ) %>% 
    mutate(wage_pct_of_male = total_earnings_female / total_earnings_male)
}
```

```{r}
jobs_gender %>% 
  group_by(year, major_category) %>% 
  summarize_jobs_gender() %>% 
  mutate(major_category = fct_reorder(major_category, -total_earnings)) %>% 
  ggplot(aes(year, total_earnings, color = major_category)) + 
  geom_line()
```

```{r}
jobs_gender %>% 
  group_by(year, major_category) %>% 
  summarize_jobs_gender() %>%
  mutate(major_category = fct_reorder(major_category, -wage_pct_of_male)) %>% 
  ggplot(aes(year, wage_pct_of_male, color = major_category)) +
  geom_line()
```

```{r}
## minor category grouping
by_minor_category_2016 <- jobs_gender %>% 
  filter(year == 2016) %>% 
  group_by(major_category, minor_category) %>% 
  summarize_jobs_gender() %>% 
  ungroup()
```

```{r}
p <- jobs_gender %>%
  filter(year == 2016) %>% 
  filter(major_category == "Healthcare Practitioners and Technical") %>% 
  arrange(desc(wage_percent_of_male)) %>% 
  ggplot(aes(total_workers, 
             workers_female / total_workers, 
             color = total_earnings_female / total_earnings_male, 
             label = occupation)) + 
  geom_point() + 
  scale_x_log10() + 
  scale_color_gradient2(low = "red", 
                        high = "blue", 
                        midpoint = .85, 
                        mid = "pink") + 
  labs(x = "Total # of workers", 
       y = "% of female workers", 
       color = "% of female median salary out earnings out of male earnings") +
  scale_x_continuous(labels = scales::percent_format()) +
  scale_y_continuous(labels = scales::percent_format())
  
library(plotly)
  ggplotly(p)
  
```
```{r}
q <- jobs_gender %>%
  filter(year == 2016) %>% 
  filter(major_category == "Healthcare Practitioners and Technical") %>% 
  arrange(desc(wage_percent_of_male)) %>% 
  ggplot(aes(workers_female / total_workers, 
             total_earnings_female / total_earnings_male,
             size = total_workers,
             label = occupation)) + 
  geom_point() + 
  scale_size_continuous(range = c(1, 10)) +
  labs(size = "Total # of workers", 
       x = "% of workers reported as female", 
       y = "% of female median salary out of male") +
  scale_x_continuous(labels = scales::percent_format()) +
  scale_y_continuous(labels = scales::percent_format())

library(plotly)
ggplotly(q)
```
```{r}
r <- jobs_gender %>%
  filter(year == 2016, 
         total_workers >= 2000) %>% 
  filter(major_category == "Computer, Engineering, and Science") %>% 
  arrange(desc(wage_percent_of_male)) %>% 
  ggplot(aes(workers_female / total_workers, 
             total_earnings_female / total_earnings_male,
             color = minor_category, 
             size = total_workers,
             label = occupation)) + 
  geom_point() + 
  scale_size_continuous(range = c(1, 10)) +
  labs(size = "Total # of workers", 
       x = "% of workers reported as female", 
       y = "% of female median salary out of male") +
  scale_x_continuous(labels = scales::percent_format()) +
  scale_y_continuous(labels = scales::percent_format())

ggplotly(r)
```

